directive @auth(requires: [Role!]!) on FIELD_DEFINITION

type Query {
	users: [User!]! @auth(requires: [PositionLead, Coordinator])
	sections: [Section!]! @auth(requires: [Responder, PositionLead, Coordinator])
}

type Mutation {
	apply(application: ApplicationInput!): ResponderApplicationResponse
		@auth(requires: [AuthenticatedUser])
	approveApplication(
		approval: ApplicationApproval!
	): ResponderApplicationResponse @auth(requires: [Coordinator])
	rejectApplication(
		rejection: ApplicationRejection!
	): ResponderApplicationResponse @auth(requires: [Coordinator])
	resetApplication(name: String!): ResponderApplicationResponse
		@auth(requires: [Coordinator])
}

interface Response {
	code: String!
	success: Boolean!
	message: String!
}

type ResponderApplicationResponse implements Response {
	code: String!
	success: Boolean!
	message: String!
	user: User
}

type Section {
	name: SectionName!
	positions: [Position!]!
}

type Position {
	name: PositionName!
	section: Section!
}

type User {
	name: String!
	email: String!
	role: Role!
	position: Position
	application: Application
}

input ApplicationInput {
	name: String!
	email: String!
	position: Position!
}

type Application {
	position: Position!
	status: ApplicationStatus!
	rejectionReason: String
}

input ApplicationApproval {
	userName: String!
	position: Position!
}

input ApplicationRejection {
	userName: String!
	position: Position!
	reason: String
}

enum ApplicationStatus {
	Unknown
	Approved
	Pending
	Rejected
}

enum Role {
	AuthenticatedUser
	PositionLead
	Coordinator
	Responder
}
