directive @auth(requires: [Role!]!) on FIELD_DEFINITION

type Query {
	users: [User!]! @auth(requires: [PositionLead])
	sections: [Section!]! @auth(requires: [Responder])
}

type Mutation {
	register(user: NewUser!): UserRegistrationResponse
		@auth(requires: [Responder])
	approve(approval: RegistrationApproval!): UserRegistrationResponse
		@auth(requires: [PositionLead])
	reject(rejection: RegistrationRejection!): UserRegistrationResponse
		@auth(requires: [PositionLead])
}

# recommended mutation response type, per:
#  https://www.apollographql.com/docs/apollo-server/schema/schema#structuring-mutation-responses
interface Response {
	code: String!
	success: Boolean!
	message: String!
}

type UserRegistrationResponse implements Response {
	code: String!
	success: Boolean!
	message: String!
	user: User
}

type Section {
	name: SectionName!
	positions: [Position!]!
}

type Position {
	name: PositionName!
	section: Section!
}

type User {
	name: String!
	email: String!
	role: Role!
	status: RegistrationStatus
	position: Position
	registrations: [RegistrationOutcome]
}

input NewUser {
	name: String!
	email: String!
	position: Position!
}

type RegistrationOutcome {
	position: Position!
	approver: String!
	date: String!
	status: RegistrationStatus!
	rejectionReason: String
}

input RegistrationApproval {
	approver: String!
	userName: String!
	position: Position!
}

input RegistrationRejection {
	approver: String!
	userName: String!
	position: Position!
	reason: String
}

enum RegistrationStatus {
	Unknown
	Approved
	ApprovalPending
	ApprovalRejected
}

enum Role {
	PositionLead
	Coordinator
	Responder
}
